# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/bot"
bin = "tmp/main"
full_bin = "tmp/main"
delay = 1000
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "logs"]
exclude_file = ["*_test.go"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

